version: 2.1

# Random values sourced from https://ramenipsum.herokuapp.com/

jobs:
  build:
    resource_class: small
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Print env var from step
          command: |
            # should NOT be masked here
            printenv RAMEN
            
            # should NOT be masked; we should see output as-is
            echo "I love Wood ear mushroom pork bones !"

          environment:
            RAMEN: 'Wood ear mushroom pork bones'
      - run:
          name: Print env var from project
          command: |
            # NOTE: I have set PROJECT_RAMEN project env var to "chilli sesame oil chopped onions lard"
            # should be masked here
            printenv PROJECT_RAMEN
            
            # sanity check
            [ "${PROJECT_RAMEN}" = "chilli sesame oil chopped onions lard" ]
            
            # should be masked; we should see "I love *****[...]"
            echo "I love chilli sesame oil chopped onions lard !"
